StructSure-LastProject/StructSure

- Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/Cs108Connector.kt
- Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
- Android/app/src/main/java/fr/uge/structsure/retrofit/RetrofitInstance.kt
- Android/app/src/main/java/fr/uge/structsure/startScan/data/ResultEntity.kt
- Android/app/src/main/java/fr/uge/structsure/startScan/data/ResultSensors.kt
- Android/app/src/main/java/fr/uge/structsure/startScan/data/ScanEntity.kt
- Android/app/src/main/java/fr/uge/structsure/startScan/data/dao/ResultDao.kt
- Android/app/src/main/java/fr/uge/structsure/startScan/data/dao/ScanDao.kt
- Android/app/src/main/java/fr/uge/structsure/startScan/domain/ScanViewModel.kt
- Android/app/src/main/java/fr/uge/structsure/startScan/presentation/MainScreenStartSensor.kt
Sauvegarde des interrogations sur RoomDB dans la table resultSensor.
> #79 sauvegarde des interrogation en local

- Android/app/src/main/AndroidManifest.xml
- Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
- Android/app/src/main/java/fr/uge/structsure/retrofit/StructureApi.kt
- Ajout de la permission de détection des appareils bluetooth pour SDK >= 31 et permission de localisation pour SDK < 31
- Fix de l'url de l'api structure
> Add location authorization and and fix structure endpoints

- Backend/src/main/java/fr/uge/structsure/StructSureBackendApplication.java
- Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
- Backend/src/main/java/fr/uge/structsure/config/SpringSecurityConfig.java
- Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
- Backend/src/main/resources/application.properties
Correction du problème de connexion en associant le front SolidJS et le back Spring:
- Suppression de la popup par défaut de spring
- Fix du crash pour cause de caractère invalide dans le JWT
- Gestion améliorée des url statiques: tout ce qui ne commence pas par "/api" est renvoyé au frontend
> #na spring security upgrade

- Backend/src/main/java/fr/uge/structsure/config/CorsConfig.java
- Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/UserAccountResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/entities/Role.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Frontend/src/components/AccountDetails.jsx
- Frontend/src/components/AdminPanelBody.jsx
- Frontend/src/index.css
Données dynamiques des utilisateurs sur la page admin.
> #115 liste des comptes dynamique

- Frontend/src/components/AccountDetails.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
- Frontend/src/components/AdminPanelBody.jsx
- Frontend/src/components/AdminPanelBottom.jsx
- Frontend/src/components/EditAccountModal.jsx
- Frontend/src/components/StructureNameCard.jsx
- Frontend/src/pages/AdminPanel.jsx
Page "Compte Admin" avec le modal statique
> #119 modale ajout de compte

- .github/workflows/Build.yaml
> add dev env

- Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
- Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
- Backend/src/main/java/fr/uge/structsure/dto/sensors/SensorDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/structure/AllStructureResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/repositories/ResultRepository.java
- Backend/src/main/java/fr/uge/structsure/services/SensorService.java
- Backend/src/main/java/fr/uge/structsure/services/StructureService.java
- Backend/src/main/java/fr/uge/structsure/utils/StateEnum.java
- Frontend/src/components/StructureDetailBody.jsx
- Frontend/src/components/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetailNote.jsx
- Frontend/src/components/StructureDetailRow.jsx
- Frontend/src/pages/AdminPanel.jsx
Api that returns list of the sensors is working, and also the frontend that shows the sensors is also done
> #108 Liste des capteurs dynamique

- Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
- Frontend/src/App.jsx
- Frontend/src/components/AccountDetails.jsx
- Frontend/src/components/AdminPanel/AddAccountModal.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
- Frontend/src/components/AdminPanelBody.jsx
- Frontend/src/components/Header.jsx
- Frontend/src/components/StructureNameCard.jsx
- Frontend/src/hooks/vaildateUserAccountForm.js
Validation de la modale d'ajout de compte
> #120 validation de la modale ajout de compte

- Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
- Android/app/src/main/java/fr/uge/structsure/retrofit/RetrofitInstance.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/cache/SensorCache.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ResultDao.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ScanDao.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/ScanWeather.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorState.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorsList.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/data/Sensor.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
Affichage des données dynamiques sur la page de scan et mise à jour des données lorsqu'un nouveau capteur est lu.
Cela implique aussi l'affichage des écrans d'alerte
PS: la BDD n'est pas encore à jour avec des données réels
> #91 mise a jour affichage

- Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
- Backend/src/main/java/fr/uge/structsure/entities/Role.java
- Backend/src/main/java/fr/uge/structsure/exceptions/ErrorIdentifier.java
- Backend/src/main/java/fr/uge/structsure/exceptions/ErrorMessages.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Backend/src/main/java/fr/uge/structsure/utils/userAccountRequestValidation/UserAccountRequestValidation.java
- Frontend/src/components/AdminPanel/AddAccountModal.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
- Frontend/src/components/AdminPanelBody.jsx
- Frontend/src/hooks/useFetch.js
- Frontend/src/hooks/vaildateUserAccountForm.js
Sauvegarde de l'ajout de compte côté serveur
> #121-Sauvegarde de l'ajout de compte côté serveur

- .github/workflows/Test.yaml
- .gitignore
- Frontend/package.json
- Frontend/src/test/Home.test.jsx
> add Test CI

- Backend/src/main/java/fr/uge/structsure/StructSureBackendApplication.java
- Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Backend/src/test/java/fr/uge/structsure/services/AccountServiceTest.java
Création du compte SuperAdmin à l'initialisation de l'application (ou au lancement si un tel compte n'existe pas encore).
Son mot de passe temporaire est généré aléatoirement et affiché dans la console au premier lancement (et doit être changé par la suite).
> #162 Ajout du super admin par défaut

- Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/UserStructureAccessRequestDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/StructurePermission.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/UpdateUserStructureAccessResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/entities/Account.java
- Backend/src/main/java/fr/uge/structsure/entities/Structure.java
- Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
- Backend/src/main/java/fr/uge/structsure/repositories/AccountRepository.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Backend/src/main/java/fr/uge/structsure/services/AccountStructureService.java
Limiter l'accès aux ouvrages aux membres autorisés
> #174 Restrictions d'acces 

- Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
- Frontend/src/components/SensorStatusColorGen.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/index.css
Implémenter statiquement le volet des détails d'un capteur qui s'affiche au clic sur un capteur de la page d'ouvrage.
Afficher les vraies données dans le volet des détails du capteur
> #170 volet de capteur statique & #171 Volet de capteur dynamique(pas plan)

- Frontend/src/components/Pagination.jsx
- Frontend/src/components/SensorFilter.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
Interface statique de tri et filtre des capteurs, ainsi que la pagination
> #109 Interface de filtre et tri des capteurs 

- Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
- Backend/src/main/java/fr/uge/structsure/dto/sensors/SensorByStructureResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
- Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
- Backend/src/main/java/fr/uge/structsure/services/SensorService.java
- Frontend/src/components/Pagination.jsx
- Frontend/src/components/SensorFilter.jsx
- Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetail/StructureDetailRow.jsx
Rendre le filtrage et tri des données dynamique ainsi que la pagination
> #110 filtre et tri dynamique des capteurs

- Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/PlanTree.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/cache/SensorCache.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorState.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
- Android/app/src/main/java/fr/uge/structsure/ui/theme/Color.kt
Modale de capteur dynamique. Les données affichés dans la modales sont connectés avec la bdd 
PS : les images des vrais plans sélectionnés ne sont pas encore affichés dynamiquement dans la modale.
> #160 modale capteur dynamique

- Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
- Backend/src/main/java/fr/uge/structsure/services/StructureService.java
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailEdit.jsx
- Frontend/src/components/StructureDetail/StructureDetailHead.jsx
- Frontend/src/components/StructureDetail/StructureDetailNote.jsx
- Frontend/src/components/StructureDetail/StructureDetailRow.jsx
- Frontend/src/hooks/useFetch.js
_ Editing the structure details working
_ Resolving bug in edit structure api
> #212-editer-un-ouvrage

- Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/GetStructureListForUserAccountsResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/StructureAcessDetails.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/StructureDetails.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Frontend/src/components/AdminPanel/AccountStructureSection.jsx
- Frontend/src/components/AdminPanel/AddAccountModal.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
- Frontend/src/components/Pagination.jsx
- Frontend/src/components/SensorPanel/Canvas.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetail/StructureDetailHead.jsx
- Frontend/src/components/StructureNameCard.jsx
Rendre la modification des droits par ouvrage dynamique depuis la modale d'édition des utilisateurs
> #173 modification des droits par ouvage

- Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
- Frontend/src/App.jsx
- Frontend/src/components/AdminPanel/AddAccountModal.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
- Frontend/src/components/AdminPanelBody.jsx
- Frontend/src/components/Login.jsx
- Frontend/src/components/LstStructureHead.jsx
- Frontend/src/components/Plan/ModalAddPlan.jsx
- Frontend/src/components/Plan/ModalEditPlan.jsx
- Frontend/src/components/Sensor/ModalAddSensor.jsx
- Frontend/src/components/SensorFilter.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
- Frontend/src/components/StructSureBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
- Frontend/src/components/StructureDetail/StructureDetailEdit.jsx
- Frontend/src/hooks/useFetch.js
Corriger le bug qui empêche d'actualier les pages `/structure/id` et permettre de recharger la page précédent après la demande de login plutôt que d'afficher constamment la page d'accueil.
> #224 redirection et login

- Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
- Backend/src/main/java/fr/uge/structsure/dto/sensors/AllSensorsByStructureRequestDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/structure/StructureDetailsResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/repositories/ResultRepository.java
- Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
- Backend/src/main/java/fr/uge/structsure/services/SensorService.java
- Backend/src/main/java/fr/uge/structsure/services/StructureService.java
- Backend/src/test/java/fr/uge/structsure/services/SensorServiceTest.java
- Frontend/src/components/Sensor/ModalAddSensor.jsx
- Frontend/src/components/SensorFilter.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetail/StructureDetailEdit.jsx
- Frontend/src/components/StructureDetail/StructureDetailHead.jsx
- Frontend/src/components/StructureDetail/StructureDetailNote.jsx
- Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
- Frontend/src/components/StructureDetail/StructureDetailRow.jsx
- Frontend/src/hooks/useFetch.js
> #7 connaitre toutes les informations liees a un scan

- Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
- Backend/src/main/java/fr/uge/structsure/entities/Account.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Backend/src/main/java/fr/uge/structsure/services/AccountStructureService.java
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
**Page** : Ouvrage, Accueil, Admin
Limiter l'accès aux ouvrages aux membres autorisés
> #211 anonymiser un compte

- Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
- Backend/src/main/java/fr/uge/structsure/dto/sensors/DeletePositionSensorResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/services/SensorService.java
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
- Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
- Frontend/src/hooks/useFetch.js
_ Delete Point dynamically done
_ Fix some other bugs
> #210 supprimer-un-point-dun-plan

- Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
- Android/app/src/main/java/fr/uge/structsure/retrofit/response/GetAllStructureResponse.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/ScanRequestDTO.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/SensorEditDTO.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/ScanWeather.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureDao.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureData.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
- Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidScanResultDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/structure/AllStructureResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/repositories/StructureRepositoryCriteriaQuery.java
- Backend/src/main/java/fr/uge/structsure/services/ScanService.java
> #209 note ouvrage

- Frontend/src/components/Sensor/ModalAddSensor.jsx
- Frontend/src/pages/Account.jsx
A chaque saisie de puce, l'enregistrer dans le LocalStorage.
Lors de la saisie suivante, on vérifie si une puce est déjà connue dans le LocalStorage, si oui, on propose la puce N+1 (en Hexa)
> #242 Suggestion de puce RFID 

- Frontend/src/components/AdminPanel/AddAccountModal.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
- Ajouter un champ de recherche pour filtrer les ouvrages dans la modale d'édition de 
- Préciser les contraintes de taille à côté du nom du champ “mot de passe” sur les modales de création et édition de compte.
> #245-Recherche-des-ouvrages

- Android/app/src/main/java/fr/uge/structsure/retrofit/LoginApi.kt
- Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
- Backend/src/main/java/fr/uge/structsure/config/JwtUtils.java
- Backend/src/main/java/fr/uge/structsure/controllers/AuthenticationController.java
- Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Backend/src/main/java/fr/uge/structsure/utils/AuthenticationType.java
- Backend/src/main/resources/application.properties
- Backend/src/test/java/fr/uge/structsure/services/AccountServiceTest.java
_ Fixing bug using Token of deleted user.
_ Creating new Endpoint for login android (/android/login) with 3 days in the expiration time
> #239-fix-JWToken

- Backend/.gitignore
- Backend/src/main/resources/application.properties
- Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
_ Zoom In button added
_ Zoom Out button added
> #243-Boutons-de-zoom-sur-un-plan

- Backend/src/main/java/fr/uge/structsure/repositories/StructureRepositoryCriteriaQuery.java
- Frontend/src/hooks/useFetch.js
_ Now state of UNKNOWN structures are now UNKNOWN as expected
> #250-ouvrage-sans-resultats-affiches-OK

- Backend/src/main/java/fr/uge/structsure/dto/sensors/EditSensorRequestDTO.java
- Backend/src/main/java/fr/uge/structsure/services/SensorService.java
- Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
**Niveau: BAS**
Le champ date d'u volet de capteur n'est pas aligné
**Niveau: MOYEN**
La date d'installation ne devrait pas être obligatoire dans le volet de capteur
> #273 Champ date du volet capteur

- Backend/src/main/java/fr/uge/structsure/controllers/AuthenticationController.java
- Backend/src/main/java/fr/uge/structsure/dto/auth/ChangePasswordRequestDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/auth/ChangePasswordResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/auth/LoginResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/entities/Account.java
- Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
- Backend/src/main/java/fr/uge/structsure/repositories/AccountRepository.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Frontend/src/components/AccountChangePassword.jsx
- Frontend/src/components/Login.jsx
- Frontend/src/pages/Account.jsx
_ Changing password is finished (backend and frontend)
> #45-Personnaliser-un-mot-de-passe-utilisateur

- Frontend/src/components/Sensor/ModalAddSensor.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetail/StructureDetailRow.jsx
_ Bug Reset Zoom when we place a sensor is resolved.
_ Close popup button added.
_ When new sensor added when can directly place it in the canvas without refresh.
> #269-popup-de-placement-de-capteur

- Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
- Frontend/src/components/Pagination.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
**Niveau: IMPORTANT**
La pagination marche mal avec les filtres (disparition, compte de page faux)
> #274 Pagination 

- Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
- Backend/src/main/java/fr/uge/structsure/config/JwtUtils.java
- Frontend/src/components/Header.jsx
- Frontend/src/components/Login.jsx
- Frontend/src/hooks/useFetch.js
Génération d'un nouveau token si la durée de vie du précédent est inférieure à la moitié de sa durée de vie totale.
La génération du nouveau token n'est donc pas faite trop souvent. On vérifie aussi si on accède à une api et non une resource statique pour être sûr que le client puisse récupérer le nouveau token.
> #239 JWToken renewal

- Frontend/src/components/AdminPanel/ConfirmationDeleteModal.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
**Page: Admin**
Une modale de confirmation doit être ajoutée avant d'anonymiser définitivement un compte utilisateur
> #288 Confirmation pour anonymiser 

- Frontend/src/components/Pagination.jsx
> #NA Pagination bug fix

- Frontend/src/components/Plan/DropdownsSection.jsx
- Frontend/src/components/Plan/ModalEditPlan.jsx
- Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
_ When we change the plan image, the image in the canvas is automaticly updated
> #268-Plan-mis-a-jour-dans-le-canvas

- Frontend/src/components/Pagination.jsx
- Frontend/src/components/Plan/DropdownsSection.jsx
- Frontend/src/components/SensorFilter.jsx
- Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetail/StructureDetailHead.jsx
- Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
_ When we choose a scan, plan and/or one of the Filter/order/date options we can refresh the page and we will not loose what we choosed before
_ When we change plan the selected scan doesn't change
> #272-Settings-in-URL

- Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
- Frontend/src/components/AccountChangePassword.jsx
- Frontend/src/components/AdminPanel/AddAccountModal.jsx
- Frontend/src/components/AdminPanel/ConfirmationDeleteModal.jsx
- Frontend/src/components/AdminPanel/EditAccountModal.jsx
- Frontend/src/components/AdminPanelBody.jsx
- Frontend/src/components/ArchiveModal.jsx
- Frontend/src/components/LstStructureHead.jsx
- Frontend/src/components/RestoreModal.jsx
- Frontend/src/components/Sensor/ModalAddSensor.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
- Frontend/src/components/StructSureBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailBody.jsx
- Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetail/StructureDetailEdit.jsx
- Frontend/src/hooks/useFetch.js
Correction d'une faille où n'importe quelle API pouvait répondre tant qu'on ne donnait pas de token (et factorisation de l'envoie du token côté frontend)
> #302 Fix jwt breach and duplication

- Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
- Backend/src/main/java/fr/uge/structsure/dto/plan/ArchiveRestorePlanResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/structure/ArchiveRestoreStructureResponseDTO.java
- Backend/src/main/java/fr/uge/structsure/repositories/SensorRepository.java
- Backend/src/main/java/fr/uge/structsure/services/PlanService.java
- Backend/src/main/java/fr/uge/structsure/services/StructureService.java
- Frontend/src/components/ArchiveModal.jsx
- Frontend/src/components/Plan/ArchiveModalHeader.jsx
- Frontend/src/components/Plan/ArchivePlanModal.jsx
- Frontend/src/components/Plan/DropdownsSection.jsx
- Frontend/src/components/Plan/ModalEditPlan.jsx
- Frontend/src/components/Plan/RestorePlanModal.jsx
- Frontend/src/components/RestoreModal.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
- Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
- Frontend/src/hooks/useFetch.js
Suggestion : Ne pas supprimer les données des capteurs (position et plan) à l'archivage, car les résultats ne s'affiche plus sur les plans dans la vue scan. Revoir les conséquences de l'archivage sur les scans/vue scan, ... 
Todo : 
- Si on archive tous les plans, ne rien afficher dans le canvas
- Si un plan est archivé, se positionné sur quel plan ?
- Faire en sorte que les sections ne se referme pas à l'archivage/restauration 
- Vérifier la pertinence des rôles
> #28 archiver un plan

- Frontend/src/components/Modal/ModalImage.jsx
_ The image is now showing when we want to edit a plan
> #-Bug-Fix-Edit-Image-Show-Existing-Image

- Backend/src/main/java/fr/uge/structsure/config/RequiresRole.java
- Backend/src/main/java/fr/uge/structsure/config/RoleFilter.java
- Backend/src/main/java/fr/uge/structsure/config/SpringSecurityConfig.java
- Backend/src/main/java/fr/uge/structsure/controllers/AndroidScanController.java
- Backend/src/main/java/fr/uge/structsure/controllers/AuthenticationController.java
- Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
- Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
- Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
- Backend/src/main/java/fr/uge/structsure/entities/Account.java
- Backend/src/main/java/fr/uge/structsure/services/AccountService.java
- Backend/src/main/java/fr/uge/structsure/services/PlanService.java
- Backend/src/main/java/fr/uge/structsure/services/SensorService.java
- Backend/src/main/java/fr/uge/structsure/services/StructureService.java
Ajout de contrôles par annotation pour restreindre les accès de certains endpoints
⚠️A besoin que #302 soit merge avant
> #305 non protected endpoints

- Frontend/src/components/SensorPanel/SensorPanel.jsx
- Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
- Frontend/src/components/StructureDetail/StructureDetailCanvasModals.jsx
- Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
:warning: Dépend de la #327
Cliquer sur le nom d'un capteur depuis le canvas ouvre le volet de capteur avec tous les détails.
Si on y modifie les informations du capteur, la liste des capteurs est mise à jour ainsi que le plan sélectionné.
> #319 clic sur un capteur

- Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
- Backend/src/main/java/fr/uge/structsure/services/StructureService.java
- Frontend/src/components/LstStructureHead.jsx
- Frontend/src/components/StructSureBody.jsx
_ Adding checks in Frontend side.
_ Correcting a bug in api create new structure.
> #316-Controles-nouvel-ouvrage

- Android/app/src/main/java/fr/uge/structsure/scanPage/data/SensorValidator.kt
- Backend/src/main/java/fr/uge/structsure/entities/SensorId.java
- Frontend/src/components/Sensor/ModalAddSensor.jsx
- Frontend/src/components/SensorPanel/SensorPanel.jsx
Caractères spéciaux dans le nom d'un capteur (ajout de capteur) ⚠️ANDROID
Echec de fusion des capteurs créés dans un scan si un capteur existe déjà avec ces puces exactement (si les deux puces sont identiques, il faut mettre le capteur à jour plutôt)
Problème lors de la création d'un capteur avec un tag existant (soucis d'espaces/majuscules ?)
Mauvais message d'erreur ??? 57
"A" devant le message d'erreur pour l'édition d'un capteur
> #322-BUG-capteurs-plans

- Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/PlansView.kt
- Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
- Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
- Backend/src/main/java/fr/uge/structsure/dto/plan/PlanMetadataDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidSensorEditDTO.java
- Backend/src/main/java/fr/uge/structsure/dto/userAccount/UserUpdateRequestDTO.java
- Backend/src/main/java/fr/uge/structsure/services/ScanService.java
- Backend/src/main/java/fr/uge/structsure/utils/DiffMaker.java
- Backend/src/main/java/fr/uge/structsure/utils/GlobalExceptionHandler.java
Suppression d'un point sur un plan et mise à jour du serveur à l'envoie du scan.
> #313 Remove sensor from plan
